### ISSUE TITLE
TypeError: 'SwigPyObject' object is not iterable

### ISSUE THREAD

**Issue by jmodrako** [rkaczorek/indi-mqtt#10]
Latest Astroberry, I've tried to run `python3 /usr/bin/indi-mqtt.py --list_topics` and got this:

`
➜ python3 /usr/bin/indi-mqtt.py --list_topics
indi-mqtt: Using configuration from /etc/indi-mqtt.conf
indi-mqtt: Starting in auto refresh mode in every 10 seconds.
indi-mqtt: Creating an instance of INDI client
indi-mqtt: Connected to MQTT server localhost:1883
indi-mqtt: Subscribed to observatory/poll topic at MQTT server localhost:1883
INDI::BaseClient::connectServer: creating new connection...
INDI::BaseClient::connectServer: Already connected.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
`

**Comment by rkaczorek** [comment]
This is caused by pyindi library which is not maintained anymore. See author's comment [here](https://github.com/geehalel/pyindi-client). As a result indi-mqtt will be replaced soon with a version rewritten in c++

**Comment by jmodrako** [comment]
Thanks for the info Radek :) I would love to use this so I'm waiting patiently :)

**Comment by jmodrako** [comment]
Am I correct that you've mentioned an update for the MQTT publishing? I swear that I've seen it somewhere on FB :)

**Comment by rkaczorek** [comment]
This project will be obsolete soon and replaced by astroberry-mqtt (to be issued soon)
Indeed I accidentally announced it with the latest update, but it was too early ;-)
At this moment you can compile it yourself from sources https://github.com/rkaczorek/astroberry-mqtt

**Comment by jmodrako** [comment]
Alright, now it's clear :)
