### ISSUE TITLE
indi-mqtt fails because of s

### ISSUE THREAD

**Issue by gnthibault** [rkaczorek/indi-mqtt#11]
Hi all,
I think the project is a very good, idea, unfortunately, I haven't been able to run the main script, because of the weird behaviour, potentially related to swig bindings:

Here is an excerpt in case someone can read through those cryptics error messages;

```
 /usr/bin/python3 /usr/bin/indi-mqtt.py
indi-mqtt: Using configuration from /etc/indi-mqtt.conf
indi-mqtt: Starting in auto refresh mode in every 10 seconds.
indi-mqtt: Creating an instance of INDI client
INDI::BaseClient::connectServer: creating new connection...
indi-mqtt: Connected to MQTT server 192.168.0.48:1883
indi-mqtt: Subscribed to observatory/poll topic at MQTT server 192.168.0.48:1883
INDI::BaseClient::connectServer: Already connected.
indi-mqtt: Connected to INDI server localhost:7624
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 461, in <module>
    observatory_json = getJSON(devices)
  File "/usr/bin/indi-mqtt.py", line 265, in getJSON
    for property in properties:
TypeError: 'SwigPyObject' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/indi-mqtt.py", line 471, in <module>
    logger.error("Unexpected error timed polling INDI server", err)
Message: 'Unexpected error timed polling INDI server'
Arguments: (TypeError("'SwigPyObject' object is not iterable"),)
swig/python detected a memory leak of type 'INDI::BaseDevice::Properties *', no destructor found.
^CTraceback (most recent call last):
  File "/usr/bin/indi-mqtt.py", line 450, in <module>
    time.sleep(1)
KeyboardInterrupt
```

pip freeze | grep pyindi
pyindi-client==0.2.8

indiserver --version
2022-01-07T20:52:01: startup: indiserver --version 
Usage: indiserver [options] driver [driver ...]
Purpose: server for local and remote INDI drivers
INDI Library: 1.9.3
Code v1.9.3-39-gce7416338. Protocol 1.7.

Thank you in advance for your help

**Comment by gnthibault** [comment]
Not an indi-mqtt issue actually
